"""create audit logs

Revision ID: bf00e251e0a2
Revises: 12834e899965
Create Date: 2026-02-24 02:25:54.221921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf00e251e0a2'
down_revision: Union[str, Sequence[str], None] = '12834e899965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index(
        "ix_audit_logs_workspace_created_at_desc",
        "audit_logs",
        ["workspace_id", "created_at"],
        postgresql_ops={"created_at": "DESC"},
    )

    op.create_index(
        "ix_audit_logs_workspace_actor_created_at_desc",
        "audit_logs",
        ["workspace_id", "actor_user_id", "created_at"],
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index(op.f('ix_documents_workspace_updated_at_desc'), table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_workspace_updated_at_desc'), 'documents', ['workspace_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index("ix_audit_logs_workspace_actor_created_at_desc", table_name="audit_logs")
    op.drop_index("ix_audit_logs_workspace_created_at_desc", table_name="audit_logs")
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
