"""create jobs

Revision ID: dae28a3f4585
Revises: bf00e251e0a2
Create Date: 2026-02-26 04:43:27.253173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dae28a3f4585'
down_revision: Union[str, Sequence[str], None] = 'bf00e251e0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed')", name='ck_jobs_status'),
    sa.CheckConstraint("type IN ('export')", name='ck_jobs_type'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'type', 'idempotency_key', name='uq_jobs_workspace_type_idempotency')
    )
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    op.create_index(
        "ix_jobs_workspace_status_created_at",
        "jobs",
        ["workspace_id", "status", "created_at"],
    )
    op.drop_index(op.f('ix_audit_logs_workspace_actor_created_at_desc'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_created_at_desc'), table_name='audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_workspace_created_at_desc'), 'audit_logs', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_actor_created_at_desc'), 'audit_logs', ['workspace_id', 'actor_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_index("ix_jobs_workspace_status_created_at", table_name="jobs")
    op.drop_table('jobs')
    # ### end Alembic commands ###
